export const STATUS_CODE = {
  OK: 200,
  CLIENT_ERROR: 400,
  NOT_FOUND: 404,
  SERVER_ERROR: 500,
  TRANSLATE_ERROR: 'TRANSLATE_FAIL',
};

export const STATUS_MSG = {
	SERVER_ERROR : 'SERVER_ERROR',
	CLIENT_ERROR : 'CLIENT_ERROR',
	OK : 'SUCCESS',
	UNKNOWN_ERROR: 'UNKNOWN_ERROR'
}


